#!/usr/bin/env bash

#    ----------------------------------------------------------------------
#    Copyright © 2025  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
        "env")")"
_lib="$( \
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" 2>/dev/null || \
  source \
    "${_crash_bash}"

_usr_get() {
  local \
    _bin
  _bin="$( \
    dirname \
      "$(command \
           -v \
	   "env")")"
  dirname \
    "${_bin}"
}

_global_variables() {
  creation_date=""
  app_id=""
  game_title=""
  game_pkgdesc=""
  game_uuid=""
  game_launcher=""
  game_platform=""
  game_lang=""
  template_file=""
  desktop_file=""
  command_file=""
  game_settings=""
  fullscreen_enabled=""
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    "sed"
  _check_cmd \
    "cp" \
    "coreutils"
}

_desktop_file_create() {
  local \
    _game_title="${1}" \
    _app_id="${2}" \
    _game_command="${3}" \
    _game_pkgdesc="${4}" \
    _game_uuid="${5}" \
    _game_launcher="${6}" \
    _game_platform="${7}" \
    _game_lang="${8}" \
    _template_file="${9}" \
    _output_file="${10}" \
    _usr \
    _templates_dir \
    _msg=()
  _msg=(
    "Preparing '${_game_title}' desktop file."
  )
  _msg_info \
    "${_msg[*]}"
  if [[ "${_template_file}" == "" ]]; then
    _usr="$( \
      _usr_get)"
    _templates_dir="${_usr}/share/videogame-launcher/templates"
    _template_file="${_templates_dir}/${_game_platform}.desktop"
  fi
  if [[ "${_output_file}" == "" ]]; then
    _output_file="$( \
      pwd)/${_app_id}.desktop"
  fi
  _msg=(
    "Copying template"
    "file '${_template_file}'."
  )
  _msg_info \
    "${_msg[*]}"
  cp \
    "${_template_file}" \
    "${_output_file}"
  sed \
    -i \
    "s/%_game_title%/${_game_title}/g" \
    "${_output_file}"
  sed \
    -i \
    "s/%_game_pkgdesc%/${_game_pkgdesc}/g" \
    "${_output_file}"
  sed \
    -i \
    "s/%_app_id%/${_app_id}/g" \
    "${_output_file}"
  sed \
    -i "s/%_game_uuid%/${_game_uuid}/g" \
    "${_output_file}"
  sed \
    -i \
    "s/%_game_launcher%/${_game_launcher}/g" \
    "${_output_file}"
  sed \
    -i \
    "s/%_game_platform%/${_game_platform}/g" \
    "${_output_file}"
  sed \
    -i \
    "s/%_game_lang%/${_game_lang}/g" \
    "${_output_file}"
  sed \
    -i \
    "s/%_game_command%/${_game_command}/g" \
    "${_output_file}"
}

_settings_duckstation_create() {
  local \
    _game_dir \
    _os \
    _rom_dir \
    _rom_install_dir \
    _settings_template \
    _share \
    _usr
  _os="$( \
    uname \
      -o)"
  _usr="$( \
    _usr_get)"
  _share="${_usr}/share"
  _settings_template="${_share}/videogame-launcher/configs/duckstation/settings.ini"
  _game_dir="${_usr}/games/${_app_id}"
  if [[ "${_os}" == "GNU/Linux" ]]; then
    _rom_dir="${_game_dir}"
  elif [[ "${_os}" == "Android" ]]; then
    _rom_dir="/storage/emulated/0/Android/media/${_app_id}"
  fi
  _msg_info \
    "Preparing Duckstation config file."
  cp \
    "${_settings_template}" \
    "${_game_settings}"
  sed \
    -i \
    "s|%_share%|${_share}|g" \
    "${_game_settings}"
  sed \
    -i \
    "s|%_game_dir%|${_rom_dir}|g" \
    "${_game_settings}"
}

_command_create() {
  local \
    _game_title="${1}" \
    _app_id="${2}" \
    _game_command="${3}" \
    _game_uuid="${4}" \
    _game_launcher="${5}" \
    _game_platform="${6}" \
    _game_lang="${7}" \
    _command_file="${8}" \
    _command_template \
    _msg=()
  _command_template="$( \
    _get_usr)/share/videogame-launcher/configs/launchers/launcher"
  _msg=(
    "Preparing command-line launcher."
  )
  _msg_info \
    "${_msg[*]}"
  cp \
    "${_command_template}" \
    "${_command_file}"
  sed \
    -i \
    "s/%_app_id%/${_app_id}/g" \
    "${_command_file}"
  sed \
    -i \
    "s/%_game_launcher%/${_game_launcher}/g" \
    "${_command_file}"
  sed \
    -i \
    "s/%_game_language%/${_game_lang}/g" \
    "${_command_file}"
  sed \
    -i \
    "s/%_game_platform%/${_game_platform}/g" \
    "${_command_file}"
  chmod \
    +x \
    "${_command_file}"
}

_videogame_launcher_create() {
  local \
    _game_title="${1}" \
    _app_id="${2}" \
    _game_command="${3}" \
    _game_pkgdesc="${4}" \
    _game_uuid="${5}" \
    _game_launcher="${6}" \
    _game_platform="${7}" \
    _game_lang="${8}" \
    _template_file="${9}" \
    _desktop_file="${10}" \
    _game_settings="${11}" \
    _command_file="${12}" \
    _fullscreen_enabled="${13}" \
    _game_command
  _game_command="$( \
    basename \
      "${_command_file}")"
  _desktop_file_create \
    "${_game_title}" \
    "${_app_id}" \
    "${_game_command}" \
    "${_game_pkgdesc}" \
    "${_game_uuid}" \
    "${_game_launcher}" \
    "${_game_platform}" \
    "${_game_lang}" \
    "${_template_file}" \
    "${_desktop_file}"
  _command_create \
    "${_game_title}" \
    "${_app_id}" \
    "${_game_command}" \
    "${_game_uuid}" \
    "${_game_launcher}" \
    "${_game_platform}" \
    "${_game_lang}" \
    "${_command_file}"
  if [[ "${_game_launcher}" == "duckstation" ]]; then
    _settings_duckstation_create
  fi
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "            Creation date:   ${creation_date}"
  _msg_info "               Game title:   ${game_title}"
  _msg_info "                   App ID:   ${app_id}"
  _msg_info "            Game launcher:   ${game_launcher}"
  _msg_info "            Game platform:   ${game_platform}"
  _msg_info "            Game language:   ${game_lang}"
  _msg_info "         Game description:   ${game_pkgdesc}"
  _msg_info "                Game UUID:   ${game_uuid}"
  _msg_info "            Template file:   ${template_file}"
  _msg_info "             Desktop file:   ${desktop_file}"
  _msg_info "             Command file:   ${command_file}"
  _msg_info "            Settings file:   ${game_settings}"
  _msg_info "       Fullscreen enabled:   ${fullscreen_enabled}"
}

_usage() {
  local \
    _exit="${1}" \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Seamlessly create videogame launchers.

Usage:
  ${app_name}
    <app_id>

  options:
     -e <game_launcher>     It can be 'doomretro',
                            'duckstation',
                            'fceux', 'gearboy', 'flycast',
                            'love', 'mame', 'retroarch',
                            'pcsx2', 'scummvm'.
                            Default: ${game_launcher}
     -p <game_platform>     Game platform. It can be
                            'playstation', 'arcade',
       	                    'doom', 'dreamcast', 'love',
                            'mame20'nes', 'nintendo64',
                            'gameboy', 'playstation2'
                            or 'scummvm'.
                            Default: ${game_platform}
     -l <game_lang>         Game languages.
                            Default: ${game_lang}
     -t <game_title>        Game full title.
                            Default: ${game_title}
     -U <game_uuid>         The game platform UUID.
                            Default: ${game_uuid}
     -d <description>       Game launcher description.
                            Default: ${game_pkgdesc}
     -m <template_file>     Template file to use to write
                            the launcher.
                            Default: ${template_file}
     -s <settings_file>     Output launcher's settings
                            file.
                            Default: ${game_settings}
     -o <command_file>      Output command filename.
                            Default: ${command_file}
     -f                     Whether to make the launcher offer
                            to open the game in full-screen.
                            Default: ${fullscreen_enabled}

     -h                     This message.
     -c                     Enable color output
     -v                     Enable verbose output

ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${_exit}"
}

_game_lang_auto_detect() {
  local \
    _uage \
    _lang
  _set_override \
    "game" \
    "lang" \
    "any"
}

_game_launcher_auto_detect() {
  local \
    _game_platform \
    _launcher \
    _os \
    _msg=()
  _os="$( \
    uname \
      -o)"
  _game_platform=""
  if [[ -v "override_game_platform" ]]; then
    _game_platform="${override_game_platform}"
  fi
  _launcher=""
  _msg=(
    "Detecting game launcher"
    "for platform '${_game_platform}'."
  )
  _msg_info \
    "${_msg[*]}"
  if [[ "${_os}" == "Android" ]]; then
    _launcher="retroarch"
  elif [[ "${_os}" == "GNU/Linux" ]]; then
    _launcher="duckstation"
    if [[ "${_game_platform}" == "arcade" ]]; then
      _launcher="mame"
    elif [[ "${_game_platform}" == "doom" ]]; then
      _launcher="doomretro"
    elif [[ "${_game_platform}" == "gameboy" ]]; then
      _launcher="gearboy"
    elif [[ "${_game_platform}" == "playstation2" ]]; then
      _launcher="pcsx2"
    fi
  fi
  if [[ "${_game_platform}" == "love" ]]; then
    _launcher="love"
  fi
  _set_override \
    "game" \
    "launcher" \
    "${_launcher}"
}

_dreamcast_auto_detect() {
  local \
    _dir="${1}"
}

_platform_find() {
  local \
    _platform="${1}" \
    _game_dir
  _game_dir="$( \
    _game_dir_get \
      "${app_id}")"
  _platform_game_dir="${_game_dir}/${_platform}"
  if [[ -d "${_platform_game_dir}" ]]; then
    platforms+=(
      "${_platform}"
    )
  fi
}

_retroarch_platform_auto_detect() {
  local \
    _game_path \
    _game_lang \
    _game_dir \
    _platforms=()
  _game_lang="${game_lang}"
  if [[ -v "override_game_lang" ]]; then
    _game_lang="${override_game_lang}"
  fi
  _msg_info \
    "Retroarch platform auto-detect."
  _msg_info \
    "Game path: ${_game_path}."
  if [[ "${_game_path}" == *".nes" ]]; then
    _platform="nes"
  elif [[ "${_game_path}" == *".gbc" || \
	  "${_game_path}" == *".gb" ]]; then
    _platform="gameboy"
  elif [[ "${_game_path}" == *".bin" || \
	  "${_game_path}" == *".cue" ]]; then
    _platform="playstation"
  elif [[ "${_game_path}" == *".iso" ]]; then
    _platform="playstation2"
  elif [[ "${_game_path}" == *".wad" || \
	  "${_game_path}" == *".WAD" ]]; then
    _platform="doom"
  elif [[ -d "${_game_path}" ]]; then
    _platform="scummvm"
  elif [[ "${_game_path}" == "" ]]; then
    _game_dir="$( \
      _game_dir_get \
        "${app_id}")"
    if [[ "$(ls "${_game_dir}/"*".cdi")" != "" ]]; then
      ""
    fi
  fi
}

_game_platform_auto_detect() {
  local \
    _platform
  _platform=""
  if [[ "${game_launcher}" == "doomretro" ]]; then
    _platform="doom"
  elif [[ "${game_launcher}" == "duckstation" ]]; then
    _platform="playstation"
  elif [[ "${game_launcher}" == "fceux" ]]; then
    _platform="nes"
  elif [[ "${game_launcher}" == "gearboy" ]]; then
    _platform="gameboy"
  elif [[ "${game_launcher}" == "mame" ]]; then
    _platform="arcade"
  elif [[ "${game_launcher}" == "love" ]]; then
    _platform="love"
  elif [[ "${game_launcher}" == "retroarch" ]]; then
    _retroarch_platform_auto_detect
  elif [[ "${game_launcher}" == "$(_lower \
	                             "pcsx2")"* ]]; then
    _platform="playstation2"
  elif [[ "${game_launcher}" == "scummvm" ]]; then
    _platform="scummvm"	
  fi
  _set_override \
    "game" \
    "platform" \
    "${_platform}"
}

_template_file_auto_detect() {
  local \
    _configs \
    _template_file
  _configs="$( \
    _get_usr)/share/videogame-launcher/configs"
  _template_file="${_configs}/launchers/${game_platform}-template.desktop"
  _set_override \
    "template" \
    "file" \
    "${_template_file}"
}

_set_overrides() {
  local \
    _app_id \
    _pwd
  _pwd="$( \
    pwd)"
  _app_id="${app_id}"
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  _set_override \
    "creation" \
    "date" \
    "$(_get_date_human)"
  _game_launcher_auto_detect
  _game_platform_auto_detect
  _game_lang_auto_detect
  _template_file_auto_detect
  _set_override \
    "desktop" \
    "file" \
    "${_pwd}/${app_id}.desktop"
  _set_override \
    "command" \
    "file" \
    "${_pwd}/${_app_id}"
  _set_override \
    "game" \
    "settings" \
    "${_pwd}/${_app_id}.settings.ini"
  _set_override \
    "fullscreen" \
    "enabled" \
    "n"
  _set_override \
    "game" \
    "uuid" \
    ""
  _set_override \
    "game" \
    "title" \
    "${_app_id}"
  _set_override \
    "game" \
    "pkgdesc" \
    "Videogame for ${game_platform}."
}

_globals
_global_variables
_requirements
while \
  getopts \
    'U:e:p:l:t:s:fd:m:o:cvh?' \
    arg; do
  case \
    "${arg}" in
    U) \
      override_game_uuid="${OPTARG}" ;;
    e) \
      override_game_launcher="${OPTARG}" ;;
    p) \
      override_game_platform="${OPTARG}" ;;
    l) \
      override_game_lang="${OPTARG}" ;;
    t) \
      override_game_title="${OPTARG}" ;;
    s) \
      override_game_settings="${OPTARG}" ;;
    f) \
      override_fullscreen_enabled="y" ;;
    d) \
      override_game_pkgdesc="${OPTARG}" ;;
    m) \
      override_template_file="${OPTARG}" ;;
    o) \
      override_command_file="${OPTARG}" ;;
    c) \
      override_color="y" ;;
    v) \
      override_quiet="n" ;;
    h|?) \
      _set_overrides
      _usage \
        0 ;;
    *) \
      _msg_error \
        "Invalid argument '${arg}'" \
        0
      _usage \
        1 ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( $# < 1 )); then
  _msg_error \
    "No Application ID given." \
    0
  _set_overrides
  _usage \
    1
fi
if (( 0 < $# )); then
  app_id="${1}"
fi
_set_overrides
_show_config
app_opts=(
  "${game_title}"
  "${app_id}"
  "${game_pkgdesc}"
  "${game_uuid}"
  "${game_launcher}"
  "${game_platform}"
  "${game_lang}"
  "${template_file}"
  "${desktop_file}"
  "${game_settings}"
  "${command_file}"
  "${fullscreen_enabled}"
)
_videogame_launcher_create \
  "${app_opts[@]}"
