#!/usr/bin/env bash

#    ----------------------------------------------------------
#    Copyright © 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------
#
#    This program is free software: you can redistribute it
#    and/or modify it under the terms of the GNU Affero
#    General Public License as published by the Free Software
#    Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be
#    useful, but WITHOUT ANY WARRANTY; without even the
#    implied warranty of MERCHANTABILITY or FITNESS FOR A
#    PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero
#    General Public License along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
        -v \
        "env")")"
_lib="$(
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" 2>/dev/null || \
  source \
    "${_crash_bash}"

_usr_get() {
  local \
    _bin
  _bin="$(
    dirname \
      "$(command \
           -v \
	   "env")")"
  dirname \
    "${_bin}"
}

_global_variables() {
  launch_date=""
  app_id=""
  game_launcher=""
  game_platform=""
  game_lang=""
  game_hud=""
  game_settings=""
  game_writable=""
  fullscreen_enabled=""
  color=""
  quiet=""
}

_requirements() {
  true
}

_doomretro_requirements() {
  _check_cmd \
    'doomretro' \
    'doomretro'
}

_dosbox_requirements() {
  _check_cmd \
    'dosbox'
}

_duckstation_requirements() {
  _check_cmd \
    'duckstation-nogui' \
    'duckstation'
}

_fceux_requirements() {
  _check_cmd \
    'fceux'
}

_flashplayer_requirements() {
  _check_cmd \
    'flashplayer'
}

_flycast_requirements() {
  _check_cmd \
    'flycast'
}

_fs-uae_requirements() {
  _check_cmd \
    "fs-uae"
}

_gearboy_requirements() {
  _check_cmd \
    'gearboy'
}

_love_requirements() {
  local \
    _msg=() \
    _love_found \
    _os
  _os="$(
    uname \
      -o)"
  if [[ "${_os}" == "Android" ]]; then
    _check_cmd \
      "termux-open" \
      "termux-tools"
    _check_cmd \
      "pacman"
    _love_found="$(
      pacman \
        -Q \
        "love-android")"
    if [[ "${_love_found}" == "" ]]; then
      _msg=(
        "Not found love for Android."
      )
      _msg_error \
        "${_msg[*]}" \
        0
      _check_cmd \
        "su" \
        "tsu"
    fi
  elif [[ "${_os}" == "GNU/Linux" ]]; then
    _check_cmd \
      "love"
  fi
}

_mame_requirements() {
  local \
    _apple2_dir \
    _data_dir \
    _lc_dir
  _check_cmd \
    'mame'
  _data_dir="$(
    _usr_get)/share"
  if [[ "${_game_platform}" == "apple2" ]]; then
    _apple2_dir="${_data_dir}/apple2"
    if [[ ! -d "${_apple2_dir}" ]]; then
      _msg=(
        "Directory '${_apple2_dir}'"
        "does not exist, the game will"
        "probably not start."
      )
      _msg_warning \
        "${_msg[*]}"
    fi
  elif [[ "${_game_platform}" == "system7" ]]; then
    _lc_dir="${_data_dir}/mac-lc"
    if [[ ! -d "${_lc_dir}" ]]; then
      _msg=(
        "Directory '${_lc_dir}'"
        "does not exist, the game will"
        "probably not start."
      )
      _msg_warning \
        "${_msg[*]}"
    fi
  fi
}

_openmsx_requirements() {
  _check_cmd \
    'openmsx'
}

_pcsx2_requirements() {
  local \
    _pcsx2 \
    _pcsx2_pkgname
  # Maybe at some point Android
  # will be blessed with PlayStation 2
  # support.
  _pcsx2="$(
    _pcsx2_auto_detect)"
  _pcsx2_pkgname="${_pcsx2}"
  if [[ "${_pcsx2}" == "PCSX2" ]]; then
    _pcsx2_pkgname="pcsx2"
  fi
  _check_cmd \
    "${_pcsx2}" \
    "${_pcsx2_pkgname}"
  if [[ ! -d "$(_usr_get)/share/ps2/bios" ]]; then
    _msg_error \
      "Please install 'ps2-bios'." \
      1
  fi
}

_pcsx2_auto_detect() {
  local \
    _cpuinfo \
    _pcsx2 \
    _sse3 \
    _sse4
  # Maybe at some point Android
  # will be blessed with PlayStation 2
  # support.
  _sse3="$(
    cat \
      "/proc/cpuinfo" |
      grep \
        "^flags" |
        grep \
          "\bsse3\b")"
  _sse4="$(
    cat \
      "/proc/cpuinfo" |
      grep \
        "^flags" |
        grep \
          "\bsse4\b")"
  if [[ "${_sse3}" == "" ]]; then
    _pcsx2="pcsx2-1.6"
  fi
  if [[ "${_sse3}" != "" ]]; then
    _pcsx2="pcsx2-1.7"
  fi
  if [[ "${_sse4}" != "" ]]; then
    _pcsx2="PCSX2"
  fi
  echo \
    "${_pcsx2}"
}

_retroarch_requirements() {
  local \
    _os
  _os="$(
    uname \
      -o)"
  if [[ "${_os}" == "Android" ]]; then
    _check_cmd \
      'su' \
      'tsu'
  elif [[ "${_os}" == "GNU/Linux" ]]; then
    _check_cmd \
      "retroarch"
  fi
}

_ruffle_requirements() {
  local \
    _os
  _os="$(
    uname \
      -o)"
  if [[ "${_os}" == "GNU/Linux" ]]; then
  _check_cmd \
    'ruffle'
  fi
}

_scummvm_requirements() {
  _check_cmd \
    'scummvm'
}

_snes9x_requirements() {
  _check_cmd \
    'snes9x'
}

_game_dir_get() {
  local \
    _app_id="${1}" \
    _dir
  _dir="$(
    _usr_get)/games/${_app_id}"
  echo \
    "${_dir}"
}

_game_path_get() {
  local \
    _app_id="${1}" \
    _lang="${2}" \
    _game_dir \
    _path \
    _msg=()
  _game_dir="$(
    _game_dir_get \
      "${_app_id}")"
  _path="${_game_dir}/${_lang}"
  if [[ ! -d "${_path}" ]]; then
    if [[ ! -f "${_path}" ]]; then
      _path="${_game_dir}/any"
      _msg=(
        "No support for language '${_lang}'."
        "Running default language 'any'."
      )
      _msg_warning \
        "${_msg[*]}"
      if [[ ! -d "${_path}" ]]; then
        _msg=(
          "Found no file to launch."
        )
	_msg_error \
          "${_msg[*]}" \
	  0
      fi
    fi
    _game_path="$(
      cat \
        "${_path}" || \
      true)"
  elif [[ -d "${_path}" ]]; then
    _game_path="${_path}"
  fi
  _game_path="$(
    realpath \
      "${_game_path}")"
}

_doomretro_launch() {
  local \
    _app_id="${1}" \
    _lang="${2}" \
    _fullscreen="${3}" \
    _game_path \
    _doomretro_opts=()
  _game_path_get \
    "${_app_id}" \
    "${_lang}"
  if [[ "${_fullscreen}" == "y" ]]; then
    _doomretro_opts+=(
      --fullscreen
    )
  fi
  doomretro \
    "${_doomretro_opts[@]}" \
    "${_game_path}"
}

_dosbox_launch() {
  local \
    _app_id="${1}" \
    _lang="${2}" \
    _fullscreen="${3}" \
    _game_path \
    _dosbox_opts=()
  _game_path_get \
    "${_app_id}" \
    "${_lang}"
  if [[ "${_fullscreen}" == "y" ]]; then
    _dosbox_opts+=(
      --fullscreen
    )
  fi
  dosbox \
    "${_dosbox_opts[@]}" \
    "${_game_path}"
}

_duckstation_launch() {
  local \
    _app_id="${1}" \
    _lang="${2}" \
    _settings="${3}" \
    _fullscreen="${4}" \
    _duckstation_opts=() \
    _game_path \
    _msg=()
  _game_path_get \
    "${_app_id}" \
    "${_lang}"
  _msg_info \
    "Running '${_game_path}'."
  _duckstation_opts=(
    -settings
      "${_settings}"
  )
  if [[ "${_fullscreen}" == "y" ]]; then
    _duckstation_opts+=(
      -fullscreen
    )
  fi
  _msg=(
    "Running 'duckstation-nogui'"
    "with options '${_duckstation_opts[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
  duckstation-nogui \
    "${_duckstation_opts[@]}" \
    "${_game_path}"
}

_fceux_launch() {
  local \
    _app_id="${1}" \
    _lang="${2}" \
    _fullscreen="${3}" \
    _game_path \
    _fceux_bios \
    _fceux_home \
    _fceux_sys_bios \
    _fceux_opts=() \
    _share \
    _msg=()
  _fceux_home="${HOME}/.fceux"
  _fceux_bios="${_fceux_home}/disksys.rom"
  _game_path_get \
    "${_app_id}" \
    "${_lang}"
  if [[ "${_fullscreen}" == "y" ]]; then
    _fceux_opts+=(
      --fullscreen
    )
  fi
  if [[ "${_game_platform}" == "famicom" ]]; then
    if [[ ! -e "${_fceux_bios}" ]]; then
      _share="$(
        _get_usr)/share"
      _fceux_sys_bios="${_share}/famicom/bios/DISKSYS.ROM"
      if [[ ! -e "${_fceux_sys_bios}" ]]; then
        _msg=(
          "FamiCom BIOS must be installed"
          "at location '${_fceux_sys_bios}'."
          "If you don't know where to get"
          "one you can type"
          "'ur famicom-bios'."
          "For more information check"
          "<https://github.com/themartiancompany/ur>."
        )
        _msg_error \
          "${_msg[*]}" \
          1
      fi
      if [[ ! -d "${_fceux_home}" ]]; then
        mkdir \
          -p \
          "${_fceux_home}"
      fi
      cp \
        "${_fceux_sys_bios}" \
        "${_fceux_bios}"
    fi
  fi
  fceux \
    "${_fceux_opts[@]}" \
    "${_game_path}"
}

_flashplayer_launch() {
  local \
    _app_id="${1}" \
    _lang="${2}" \
    _fullscreen="${3}" \
    _game_path \
    _flashplayer_opts=()
  _game_path_get \
    "${_app_id}" \
    "${_lang}"
  if [[ "${_fullscreen}" == "y" ]]; then
    _flashplayer_opts+=(
      --fullscreen
    )
  fi
  flashplayer \
    "${_flashplayer_opts[@]}" \
    "${_game_path}"
}

_flycast_launch() {
  local \
    _app_id="${1}" \
    _lang="${2}" \
    _fullscreen="${3}" \
    _game_path \
    _flycast_opts=()
  _game_path_get \
    "${_app_id}" \
    "${_lang}"
  if [[ "${_fullscreen}" == "y" ]]; then
    _flycast_opts+=(
      --fullscreen
    )
  fi
  flycast \
    "${_flycast_opts[@]}" \
    "${_game_path}"
}

_cyberstorm_setup() {
  local \
    _cyberstorm \
    _cyberstorm_link \
    _cyberstorm_target \
    _kickstarts
  _kickstarts="${_config_dir_user}/Kickstarts"
  _cyberstorm="cyberstormppc.rom"
  _cyberstorm_target="$(
    _usr_get)/share/amiga/cyberstorm/${_cyberstorm}"
  _cyberstorm_link="${_kickstarts}/${_cyberstorm}"
  if [[ ! -e "${_kickstarts}/${_cyberstorm}" ]]; then
    _msg=(
      "Linking system Amiga Cyberstorm"
      "Expansion Rom image in"
      "kickstarts directory '${_kickstarts}'."
    )
    _msg_info \
      "${_msg[*]}"
    mkdir \
      -p \
      "${_kickstarts}"
    ln \
      -s \
      "${_cyberstorm_target}" \
      "${_cyberstorm_link}" || \
    true
  fi
}

_settings_fs-uae_create() {
  local \
    _app_id="${1}" \
    _base_dir="${2}" \
    _game_path="${3}" \
    _configs \
    _configs_game \
    _game_dir \
    _msg=() \
    _settings \
    _settings_template \
    _share \
    _usr
  _msg=(
    "Creating game configuration."
  )
  _msg_info \
    "${_msg[*]}"
  _usr="$(
    _usr_get)"
  _game_file_name="$(
    basename \
      "${_game_path}")"
  _share="${_usr}/share"
  _configs="${_share}/${app_name}/configs"
  _settings_template="${_configs}/fs-uae/template.fs-uae"
  _configs_game="${_base_dir}/Configurations"
  _settings="${_configs_game}/${_game_file_name}.fs-uae"
  _msg=(
    "Preparing FS UAE config file."
  )
  _msg_info \
    "${_msg[*]}"
  mkdir \
    -p \
    "${_configs_game}"
  cp \
    "${_settings_template}" \
    "${_settings}"
  sed \
    -i \
    "s|%_base_dir%|${_base_dir}|g" \
    "${_settings}"
  sed \
    -i \
    "s|%_floppy_drive%|${_game_path}|g" \
    "${_settings}"
}

_fs-uae_launch() {
  local \
    _app_id="${1}" \
    _lang="${2}" \
    _fullscreen="${3}" \
    _cache_dir \
    _config_dir_user \
    _cyberstorm_img \
    _game_dir \
    _game_file_name \
    _game_path \
    _settings \
    _fs_uae_opts=()
  _game_path_get \
    "${_app_id}" \
    "${_lang}"
  _cache_dir="${HOME}/.cache/${_app_id}"
  _config_dir_user="${HOME}/.config/${_app_id}"
  _game_file_name="$(
    basename \
      "${_game_path}")"
  _game_dir="$(
    dirname \
      "${_game_path}")"
  _settings="${_config_dir_user}/Configurations/${_game_file_name}.fs-uae"
  _cyberstorm_setup
  if [[ ! -e "${_settings}" ]]; then
    mkdir \
      -p \
      "${_config_dir_user}"
    _settings_fs-uae_create \
      "${_app_id}" \
      "${_config_dir_user}" \
      "${_game_path}"
  fi
  if [[ "${_fullscreen}" == "y" ]]; then
    _fs_uae_opts+=(
      --fullscreen
    )
  fi
  fs-uae \
    "${_fs_uae_opts[@]}" \
    "${_settings}"
}

_gearboy_launch() {
  local \
    _app_id="${1}" \
    _lang="${2}" \
    _fullscreen="${3}" \
    _game_path \
    _gearboy_opts=()
  _game_path_get \
    "${_app_id}" \
    "${_lang}"
  if [[ "${_fullscreen}" == "y" ]]; then
    _gearboy_opts+=(
      # --fullscreen
    )
  fi
  gearboy \
    "${_gearboy_opts[@]}" \
    "${_game_path}"
}

_love_launch() {
  local \
    _app_id="${1}" \
    _lang="${2}" \
    _fullscreen="${3}" \
    _game_path \
    _love_opts=()
  _game_path_get \
    "${_app_id}" \
    "${_lang}"
  if [[ "${_os}" == "GNU/Linux" ]]; then
    if [[ "${_fullscreen}" == "y" ]]; then
      _love_opts+=(
        # --fullscreen
      )
    fi
    love \
      "${_love_opts[@]}" \
      "${_game_path}"
  elif [[ "${_os}" == "Android" ]]; then
    termux-open \
      "${_game_path}"
  fi
}

_hash_get() {
  local \
    _file="${1}"
  sha256sum \
    "${_file}" |
    awk \
      '{print $1}'
}

_mame_opts_get() {
  local \
    _data_dir \
    _os_img \
    _game_img
  if [[ "${_game_platform}" == "apple2" ]]; then
    _mame_opts+=(
      -rompath
        "${_rom_dir}"
      -swpath
        "${_rom_dir}"
      apple2e
      # -flop1
      #   "${_flop1}"
      "${_game_name}"
    )
  elif [[ "${_game_platform}" == "system7" ]]; then
    _os_img="${_cache_dir}/system7_0_1-color.img"
    _game_img="${_cache_dir}/${_game_name}"
    _mame_opts+=(
      maclc3
      -rompath
        "${_cache_dir}"
      -swpath
        "${_cache_dir}"
      -hard1
        "${_os_img}"
    )
    if [[ "${_os_img}" == "${_game_img}" ]]; then
      _msg=(
        "The videogame is the OS itself."
      )
      _msg_info \
        "${_msg[*]}"
    else
      _mame_opts+=(
        -flop1
          "${_game_img}"
      )
    fi
  else
    _mame_opts+=(
      -rompath
        "${_rom_dir}"
      "${_game_name}"
    )
  fi
}

_mame_writable_setup() {
  local \
    _data_dir \
    _fw_dir \
    _os_dir \
    _os_img
  _data_dir="$(
    _usr_get)/share"
  _cache_dir="${HOME}/.cache/${_app_id}"
  if [[ ! -d "${_cache_dir}" ]]; then
    _msg=(
      "Copying System 7 and game image onto"
      "user home directory."
    )
    _msg_info \
      "${_msg[*]}"
    mkdir \
      -p \
      "${_cache_dir}"
    if [[ "${_game_platform}" == "system7" ]]; then
      _fw_dir="${_data_dir}/mac-lc/mac-lc"
      _os_dir="${_data_dir}/system7/system7"
      _os_img="${_os_dir}/system7_0_1-color.img"
      cp \
        -r \
        "${_fw_dir}" \
        "${_cache_dir}/maclc520"
      cp \
        -r \
        "${_os_dir}/"* \
        "${_cache_dir}"
      cp \
        "${_rom_dir}/"* \
        "${_cache_dir}"
    fi
  fi
}

_mame_launch() {
  local \
    _app_id="${1}" \
    _lang="${2}" \
    _fullscreen="${3}" \
    _cache_dir \
    _game_path \
    _mame_opts=() \
    _rom_dir \
    _game_name \
    _msg=()
  _game_path_get \
    "${_app_id}" \
    "${_lang}"
  _rom_dir="$(
    dirname \
      "${_game_path}")"
  _game_name="$(
    basename \
      "${_game_path}")"
  if [[ "${_writable}" = "y" ]]; then
    _mame_writable_setup
  fi
  _mame_opts_get
  if [[ "${_fullscreen}" == "n" ]]; then
    _mame_opts+=(
      -window
      -nomaximize
    )
  fi
  _msg=(
    "Running MAME with options"
    "'${_mame_opts[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
  mame \
    "${_mame_opts[@]}"
}

_openmsx_launch() {
  local \
    _app_id="${1}" \
    _lang="${2}" \
    _fullscreen="${3}" \
    _game_path \
    _openmsx_opts=()
  _game_path_get \
    "${_app_id}" \
    "${_lang}"
  if [[ "${_fullscreen}" == "y" ]]; then
    _openmsx_opts+=(
      --fullscreen
    )
  fi
  openmsx \
    "${_openmsx_opts[@]}" \
    "${_game_path}"
}

_pcsx2_launch() {
  local \
    _app_id="${1}" \
    _lang="${2}" \
    _settings="${3}" \
    _fullscreen="${4}" \
    _pcsx2_opts=() \
    _game_path \
    _pcsx2 \
    _pcsx2_ver \
    _game_dir \
    _settings_system \
    _config_dir_user \
    _cache_dir
  _cache_dir="${HOME}/.cache/${_app_id}"
  _config_dir_user="${HOME}/.config/${_app_id}"
  _pcsx2="$(
    _pcsx2_auto_detect)"
  _pcsx2_ver="$(
    basename \
      "${_pcsx2}")"
  _game_path_get \
    "${_app_id}" \
    "${_lang}"
  _msg_info \
    "Running '${_game_path}'."
  _game_dir="$(
    dirname \
      "${_game_path}")"
  if [[ ! -d "${_config_dir_user}" ]]; then
    _msg=(
      "Creating game configuration."
    )
    _msg_info \
      "${_msg[*]}"
    _settings_system="${_game_dir}/inis"
    if [[ ! -d "${_settings_system}" ]]; then
      _msg=(
        "No game specific configuration"
        "files, using system defaults."
      )
      _msg_info \
        "${_msg[*]}"
      _settings_system="$(
        _usr_get)/share/${app_name}/configs"
    fi
    mkdir \
      -p \
      "${_config_dir_user}"
    cp \
      -r \
      "${_settings_system}/"* \
      "${_config_dir_user}"
  fi
  _pcsx2_opts+=(
    --fullboot
    --nogui
  )
  if [[ ! -e "${_cache_dir}/bios" ]]; then
    mkdir \
      -p \
      "${_cache_dir}/bios"
    cp \
      "$(_usr_get)/share/ps2/bios/"* \
      "${_cache_dir}/bios"
  fi
  if [[ -e "${_config_dir_user}/${_pcsx2}" ]]; then
    _bios_file="ps2-0120e-20000902.bin"
    sed \
      -i \
      "s|%_bios_dir%|${_cache_dir}/bios|g" \
      "${_config_dir_user}/${_pcsx2}/PCSX2_ui.ini"
    sed \
      -i \
      "s|%_bios_file%|${_bios_file}|g" \
      "${_config_dir_user}/${_pcsx2}/PCSX2_ui.ini"
    _pcsx2_opts+=(
      --cfgpath
        "${_config_dir_user}/${_pcsx2}"
    )
  fi
  if [[ "${_fullscreen}" == "y" ]]; then
    _pcsx2_opts+=(
      --fullscreen
    )
  fi
  "${_pcsx2}" \
    "${_pcsx2_opts[@]}" \
    "${_game_path}"
}

_retroarch_launch() {
  local \
    _app_id="${1}" \
    _platform="${2}" \
    _lang="${3}" \
    _hud="${4}" \
    _core_name \
    _os \
    _game_path \
    _cores_path \
    _platform_core_path \
    _cmd=()
  _os="$(
    uname \
      -o)"
  _game_path_get \
    "${_app_id}" \
    "${_lang}"
  _msg_info \
    "Running '${_game_path}'."
  if [[ "${_os}" == "Android" ]]; then
    _cores_path="/data/user/0/com.retroarch/cores"
    if [[ "${_platform}" == "arcade" ]]; then
      _core_name="mame2000"
    elif [[ "${_platform}" == "doom" ]]; then
      _core_name="prboom"
    elif [[ "${_platform}" == "dos" ]]; then
      _core_name="dosbox_pure"
    elif [[ "${_platform}" == "dreamcast" ]]; then
      _core_name="flycast"
    elif [[ "${_platform}" == "famicom" ]]; then
      _core_name="fceumm"
    elif [[ "${_platform}" == "mame" ]]; then
      _core_name="${_platform}arcade"
    elif [[ "${_platform}" == "mame2003" ]]; then
      _core_name="${_platform}_plus"
    elif [[ "${_platform}" == "mame2010" ]]; then
      _core_name="${_platform}"
    elif [[ "${_platform}" == "msx" ]]; then
      _core_name="blue${_platform}"
    elif [[ "${_platform}" == "nes" ]]; then
      _core_name="quick${_platform}"
    elif [[ "${_platform}" == "nintendo64" ]]; then
      _core_name="mupen64plus_next_gles2"
    elif [[ "${_platform}" == "playstation" ]]; then
      _core_name="pcsx_rearmed"
    elif [[ "${_platform}" == "gameboy" ]]; then
      _core_name="gearboy"
    elif [[ "${_platform}" == "scummvm" ]]; then
      _core_name="${_platform}"
    elif [[ "${_platform}" == "snes" ]]; then
      _core_name="snes9x"
    else
      _msg=(
        "Unknown platform '${_platform}'."
      )
      _msg_error \
        "${_msg[*]}" \
	1
    fi
    _platform_core_path="${_cores_path}/${_core_name}_libretro_android.so"
    _cmd=(
      am
        start \
          -a
            'android.intent.action.MAIN'
          -n
            'com.retroarch/.browser.retroactivity.RetroActivityFuture'
          -e
            'ROM'
            "${_game_path}"
          -e
            'LIBRETRO'
            "${_platform_core_path}"  
    )
    if [[ "${_hud}" == "y" ]]; then
    _cmd+=(
      -e
        'CONFIGFILE'
        '/storage/emulated/0/Android/data/com.retroarch/files/retroarch.cfg'
    )
    fi
    su \
      -c \
        "${_cmd[*]}"
  elif [[ "${_os}" == "GNU/Linux" ]]; then
    if [[ "${_platform}" == "dreamcast" ]]; then
      _core="mupen64plus_next"
    fi
    retroarch \
      --libretro \
      "$(_usr_get)/lib/libretro/${_core}_libretro.so" \
      "${_game_path}"
  fi
}

_ruffle_launch() {
  local \
    _app_id="${1}" \
    _lang="${2}" \
    _fullscreen="${3}" \
    _game_path \
    _ruffle_opts=() \
    _os
  _os="$(
    uname \
      -o)"
  _game_path_get \
    "${_app_id}" \
    "${_lang}"
  if [[ "${_os}" == "GNU/Linux" ]]; then
    if [[ "${_fullscreen}" == "y" ]]; then
      _ruffle_opts+=(
        --fullscreen
      )
    fi
    ruffle \
      "${_ruffle_opts[@]}" \
      "${_game_path}"
  elif [[ "${_os}" == "Android" ]]; then
    termux-open \
      "${_game_path}"
  fi
}

_scummvm_launch() {
  local \
    _app_id="${1}" \
    _lang="${2}" \
    _settings="${3}" \
    _fullscreen="${4}" \
    _game_path \
    _scummvm_opts=()
  _game_path_get \
    "${_app_id}" \
    "${_lang}"
  if [[ "${_fullscreen}" == "y" ]]; then
    _scummvm_opts+=(
      -f
    )
  fi
  _scummvm_opts+=(
    --path="${_game_path}"
  )
  scummvm \
    "${_scummvm_opts[@]}" \
    "${_settings}"
}

_snes9x_launch() {
  local \
    _app_id="${1}" \
    _lang="${2}" \
    _fullscreen="${3}" \
    _game_path \
    _snes9x_opts=()
  _game_path_get \
    "${_app_id}" \
    "${_lang}"
  if [[ "${_fullscreen}" == "y" ]]; then
    _doomretro_opts+=(
      --fullscreen
    )
  fi
  snes9x \
    "${_snes9x_opts[@]}" \
    "${_game_path}"
}

_game_launcher_opts_get() {
  if [[ "${_game_launcher}" == "doomretro" ]]; then
    _launch_opts+=(
      "${_app_id}"
      "${_lang}"
      # "${_settings}"
      "${_fullscreen}"
    )
  elif [[ "${_game_launcher}" == "dosbox" ]]; then
    _launch_opts+=(
      "${_app_id}"
      "${_lang}"
      # "${_settings}"
      "${_fullscreen}"
    )
  elif [[ "${_game_launcher}" == "duckstation" ]]; then
    _launch_opts+=(
      "${_app_id}"
      "${_lang}"
      "${_settings}"
      "${_fullscreen}"
    )
  elif [[ "${_game_launcher}" == "fceux" ]]; then
    _launch_opts+=(
      "${_app_id}"
      "${_lang}"
      "${_fullscreen}"
    )
  elif [[ "${_game_launcher}" == "flashplayer" ]]; then
    _launch_opts+=(
      "${_app_id}"
      "${_lang}"
      # "${_settings}"
      "${_fullscreen}"
    )
  elif [[ "${_game_launcher}" == "flycast" ]]; then
    _launch_opts+=(
      "${_app_id}"
      "${_lang}"
      "${_fullscreen}"
    )
  elif [[ "${_game_launcher}" == "fs-uae" ]]; then
    _launch_opts+=(
      "${_app_id}"
      "${_lang}"
      "${_fullscreen}"
    )
  elif [[ "${_game_launcher}" == "gearboy" ]]; then
    _launch_opts+=(
      "${_app_id}"
      "${_lang}"
      "${_fullscreen}"
    )
  elif [[ "${_game_launcher}" == "mame" ]]; then
    _launch_opts+=(
      "${_app_id}"
      "${_lang}"
      "${_fullscreen}"
    )
  elif [[ "${_game_launcher}" == "openmsx" ]]; then
    _launch_opts+=(
      "${_app_id}"
      "${_lang}"
      "${_fullscreen}"
    )
  elif [[ "${_game_launcher}" == "pcsx2" ]]; then
    _launch_opts+=(
      "${_app_id}"
      "${_lang}"
      "${_settings}"
      "${_fullscreen}"
    )
  elif [[ "${_game_launcher}" == "retroarch" ]]; then
    _launch_opts+=(
      "${_app_id}"
      "${_game_platform}"
      "${_lang}"
      "${_hud}"
    )
  elif [[ "${_game_launcher}" == "ruffle" ]]; then
    _launch_opts+=(
      "${_app_id}"
      "${_lang}"
      # "${_settings}"
      "${_fullscreen}"
    )
  elif [[ "${_game_launcher}" == "scummvm" ]]; then
    _launch_opts+=(
      "${_app_id}"
      "${_lang}"
      "${_settings}"
      "${_fullscreen}"
    )
  elif [[ "${_game_launcher}" == "snes9x" ]]; then
    _launch_opts+=(
      "${_app_id}"
      "${_lang}"
      # "${_settings}"
      "${_fullscreen}"
    )
  else
    _msg_error \
      "Unknown launcher '${_game_launcher}'." \
      1
  fi
}

_videogame_launcher() {
  local \
    _app_id="${1}" \
    _game_launcher="${2}" \
    _game_platform="${3}" \
    _lang="${4}" \
    _hud="${5}" \
    _settings="${6}" \
    _writable="${7}" \
    _fullscreen="${8}" \
    _launch_opts=()
  "_${_game_launcher}_requirements"
  _game_launcher_opts_get
  "_${_game_launcher}_launch" \
    "${_launch_opts[@]}"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "              Launch date:   ${launch_date}"
  _msg_info "                   App ID:   ${app_id}"
  _msg_info "            Game launcher:   ${game_launcher}"
  _msg_info "            Game platform:   ${game_platform}"
  _msg_info "            Game language:   ${game_lang}"
  _msg_info "                 Game HUD:   ${game_hud}"
  _msg_info "            Game settings:   ${game_settings}"
  _msg_info "            Writable game:   ${game_writable}"
  _msg_info "       Fullscreen enabled:   ${fullscreen_enabled}"
}

_usage() {
  local \
    _exit="${1}" \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Seamlessly launch videogames.

Usage:
  ${app_name}
    <app-id>

  options:
     -e <game-launcher>     It can be 'doomretro',
                            'dosbox', 'duckstation',
                            'fceux', 'flashplayer',
                            'flycast', 'fs-uae', 'gearboy',
                            'love', 'mame', 'openmsx',
                            'retroarch', 'ruffle',
                            'pcsx2', 'scummvm',
                            'snes9x'.
                            Default: ${game_launcher}
     -p <game-platform>     Game platform. It can be
                            'amiga, 'apple2', 'arcade',
                            'doom', 'dreamcast',
                            'famicom', 'flash',
                            'gameboy', 'love',
                            'mame', 'mame2003, 'mame2010,
                            'msx', 'nes', 'nintendo64',
                            'playstation', 'playstation2',
                            'scummvm' or 'snes'.
                            Default: ${game_platform}
     -l <game-lang>         Game languages.
                            Default: ${game_lang}
     -H                     Enables on-screen controller HUD.
                            Default: ${game_hud}
     -s <game-settings>     Depending on the selected game launcher
                            it can be a Duckstation settings file
			    or the name for a SCUMMVM game
                            platform.
                            Default: ${game_settings}
     -f                     Launch the game in full-screen.
                            Default: ${fullscreen_enabled}

     -h                     This message.
     -c                     Enable color output
     -v                     Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${_exit}"
}

_game_lang_auto_detect() {
  local \
    _uage \
    _lang
  _uage="${LANG%%.*}"
  _lang="${_uage%%_*}"
  _set_override \
    "game" \
    "lang" \
    "${_lang}"
}

_game_settings_auto_detect() {
  local \
    _launcher \
    _settings \
    _pcsx2
  _launcher="${game_launcher}"
  _settings=""
  if [[ "${_launcher}" == "duckstation" ]]; then
    _settings="$(
      _usr_get)/games/${app_id}/${app_id}.settings.ini"
  elif [[ "${_launcher}" == "pcsx2" ]]; then
    _pcsx2="$(
      _pcsx2_auto_detect)"
    _settings="${HOME}/.config/${app_id}/${_pcsx2}"
  fi
  _set_override \
    "game" \
    "settings" \
    "${_settings}"
  _set_override \
    "fullscreen" \
    "enabled" \
    "n"
}

_game_launcher_auto_detect() {
  local \
    _game_platform \
    _launcher \
    _os \
    _msg=()
  _os="$(
    uname \
      -o)"
  _game_platform=""
  if [[ -v "override_game_platform" ]]; then
    _game_platform="${override_game_platform}"
  fi
  _launcher=""
  _msg=(
    "Detecting game launcher"
    "for platform '${_game_platform}'."
  )
  _msg_info \
    "${_msg[*]}"
  if [[ "${_os}" == "Android" ]]; then
    _launcher="retroarch"
    if [[ "${_game_platform}" == "flash" ]]; then
      _launcher="ruffle"
    elif [[ "${_game_platform}" == "system7" ]]; then
      # at some point somebody will
      # build PCE for android i guess
      _launcher="retroarch"
    fi
  elif [[ "${_os}" == "GNU/Linux" ]]; then
    _launcher="duckstation"
    if [[ "${_game_platform}" == "amiga" ]]; then
      _launcher="fs-uae"
    elif [[ "${_game_platform}" == "apple2" ]]; then
      _launcher="mame"
    elif [[ "${_game_platform}" == "arcade" ]]; then
      _launcher="mame"
    elif [[ "${_game_platform}" == "doom" ]]; then
      _launcher="doomretro"
    elif [[ "${_game_platform}" == "dreamcast" ]]; then
      _launcher="flycast"
    elif [[ "${_game_platform}" == "famicom" ]]; then
      _launcher="fceux"
    elif [[ "${_game_platform}" == "flash" ]]; then
      _launcher="flashplayer"
    elif [[ "${_game_platform}" == "gameboy" ]]; then
      _launcher="gearboy"
    elif [[ "${_game_platform}" == "msx" ]]; then
      _launcher="openmsx"
    elif [[ "${_game_platform}" == "playstation2" ]]; then
      _launcher="pcsx2"
    elif [[ "${_game_platform}" == "system7" ]]; then
      _launcher="mame"
    fi
  fi
  if [[ "${_game_platform}" == "love" ]]; then
    _launcher="love"
  fi
  _set_override \
    "game" \
    "launcher" \
    "${_launcher}"
}

_dreamcast_auto_detect() {
  local \
    _dir="${1}"
}

_platform_find() {
  local \
    _platform="${1}" \
    _game_dir
  _game_dir="$(
    _game_dir_get \
      "${app_id}")"
  _platform_game_dir="${_game_dir}/${_platform}"
  if [[ -d "${_platform_game_dir}" ]]; then
    platforms+=(
      "${_platform}"
    )
  fi
}

_retroarch_platform_auto_detect() {
  local \
    _game_path \
    _game_lang \
    _game_dir \
    _platforms=() \
    _msg=()
  _game_lang="${game_lang}"
  if [[ -v "override_game_lang" ]]; then
    _game_lang="${override_game_lang}"
  fi
  _msg=(
    "Retroarch platform auto-detect."
  )
  _msg_info \
    "${_msg[*]}"
  _game_path_get \
      "${app_id}" \
      "${_game_lang}"
  _msg=(
    "Game path: ${_game_path}."
  )
  _msg_info \
    "${_msg[*]}"
  if [[ "${_game_path}" == *".EXE" ]]; then
    _platform="dos"
  elif [[ "${_game_path}" == *".bin" || \
          "${_game_path}" == *".cue" ]]; then
    _platform="playstation"
  elif [[ "${_game_path}" == *".cdi" ]]; then
    _platform="dreamcast"
  elif [[ "${_game_path}" == *".fds" ]]; then
    _platform="famicom"
  elif [[ "${_game_path}" == *".gbc" || \
          "${_game_path}" == *".gb" ]]; then
    _platform="gameboy"
  elif [[ "${_game_path}" == *".img" ]]; then
    _platform="mame"
  elif [[ "${_game_path}" == *".iso" ]]; then
    _platform="playstation2"
  elif [[ "${_game_path}" == *".mx2" ]]; then
    _platform="msx"
  elif [[ "${_game_path}" == *".nes" ]]; then
    _platform="nes"
  elif [[ "${_game_path}" == *".smc" ]]; then
    _platform="snes"
  elif [[ "${_game_path}" == *".swf" ]]; then
    _platform="flashplayer"
  elif [[ "${_game_path}" == *".wad" || \
          "${_game_path}" == *".WAD" ]]; then
    _platform="doom"
  elif [[ -d "${_game_path}" ]]; then
    _platform="scummvm"
  elif [[ "${_game_path}" == "" ]]; then
    _game_dir="$(
      _game_dir_get \
        "${app_id}")"
    if [[ "$(ls "${_game_dir}/"*".cdi")" != "" ]]; then
      _msg=(
	"Definitely not gonna have it this way."
      )
      echo \
        "${_msg[*]}"
    fi
  fi
}

_mame_platform_auto_detect() {
  local \
    _game_path \
    _game_lang \
    _game_dir \
    _platforms=() \
    _msg=()
  _game_lang="${game_lang}"
  if [[ -v "override_game_lang" ]]; then
    _game_lang="${override_game_lang}"
  fi
  _msg=(
    "MAME platform auto-detect."
  )
  _msg_info \
    "${_msg[*]}"
  _game_path_get \
      "${app_id}" \
      "${_game_lang}"
  _msg=(
    "Game path for"
    "videogame with app id"
    "${app_id}: ${_game_path}."
  )
  _msg_info \
    "${_msg[*]}"
  if [[ "${_game_path}" == *".img" ]]; then
    _platform="system7"
  else
    _platform="arcade"
  fi
}

_game_platform_auto_detect() {
  local \
    _platform
  _platform=""
  if [[ "${game_launcher}" == "doomretro" ]]; then
    _platform="doom"
  elif [[ "${game_launcher}" == "dosbox" ]]; then
    _platform="dos"
  elif [[ "${game_launcher}" == "duckstation" ]]; then
    _platform="playstation"
  elif [[ "${game_launcher}" == "fceux" ]]; then
    _platform="nes"
  elif [[ "${game_launcher}" == "flashplayer" ]]; then
    _platform="flash"
  elif [[ "${game_launcher}" == "fs-uae" ]]; then
    _platform="amiga"
  elif [[ "${game_launcher}" == "gearboy" ]]; then
    _platform="gameboy"
  elif [[ "${game_launcher}" == "love" ]]; then
    _platform="love"
  elif [[ "${game_launcher}" == "mame" ]]; then
    _mame_platform_auto_detect
  elif [[ "${game_launcher}" == "openmsx" ]]; then
    _platform="msx"
  elif [[ "${game_launcher}" == "retroarch" ]]; then
    _retroarch_platform_auto_detect
  elif [[ "${game_launcher}" == "$(_lower \
	                             "pcsx2")"* ]]; then
    _platform="playstation2"
  elif [[ "${game_launcher}" == "scummvm" ]]; then
    _platform="scummvm"	
  elif [[ "${game_launcher}" == "snes9x" ]]; then
    _platform="snes"
  fi
  _set_override \
    "game" \
    "platform" \
    "${_platform}"
}

_game_hud_auto_detect() {
  local \
    _os \
    _game_hud
  _os="$(
    uname \
      -o)"
  _game_hud="n"
  if [[ "${_os}" == "Android" ]]; then
    _game_hud="y"
  fi
  _set_override \
    "game" \
    "hud" \
    "${_game_hud}"
}

_set_overrides() {
  local \
    _app_id
  _app_id="${app_id}"
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  _set_override \
    "launch" \
    "date" \
    "$(_get_date_human)"
  _game_launcher_auto_detect
  _game_platform_auto_detect
  _game_lang_auto_detect
  _game_hud_auto_detect
  _game_settings_auto_detect
  _set_override \
    "game" \
    "writable" \
    "n"
}

_globals
_global_variables
_requirements
while \
  getopts \
    'e:p:l:H:s:f:wcvh?' \
    arg; do
  case \
    "${arg}" in
    e) \
      override_game_launcher="${OPTARG}" ;;
    p) \
      override_game_platform="${OPTARG}" ;;
    l) \
      override_game_lang="${OPTARG}" ;;
    H) \
      override_game_hud="y" ;;
    s) \
      override_game_settings="${OPTARG}" ;;
    f) \
      override_fullscreen_enabled="y" ;;
    w) \
      override_game_writable="y" ;;
    c) \
      override_color="y" ;;
    v) \
      override_quiet="n" ;;
    h|?) \
      _set_overrides
      _usage \
        0 ;;
    *) \
      _msg_error \
        "Invalid argument '${arg}'" \
        0
      _usage \
        1 ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( $# < 1 )); then
  _msg_error \
    "No Application ID given." \
    0
  _set_overrides
  _usage \
    1
fi
if (( 0 < $# )); then
  app_id="${1}"
fi
_set_overrides
_show_config
app_opts=(
  "${app_id}"
  "${game_launcher}"
  "${game_platform}"
  "${game_lang}"
  "${game_hud}"
  "${game_settings}"
  "${game_writable}"
  "${fullscreen_enabled}"
)
_videogame_launcher \
  "${app_opts[@]}"
